<?php

/** @var \Magento\Framework\Escaper $escaper */
/** @var Heroicons2Outline $heroicons */

use Magento\Framework\Escaper;
use Hyva\Heroicons2\ViewModel\Heroicons2Outline;

$heroicons = $viewModels->require(Heroicons2Outline::class);
$paymentIcons = $viewModels->require(Hyva\PaymentIcons\ViewModel\PaymentIconsLight::class);
?>
<?= $heroicons->shoppingCartHtml('w-8 h-8') ?>
<?= $heroicons->bars3Html('w-8 h-8') ?>
<?= $paymentIcons->paypalHtml('w-8 h-8') ?>