<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */

use \Blackbird\HyvaSplideJs\Api\HyvaSplideJSInterface;
$imageUrl = "https://images.unsplash.com/photo-1718043717629-6e2ce053ab96?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D";
// Or, get an image from `web/images/` in your theme:
// $imageUrl = $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banner.jpg'));
?>

<section class="splide" id="my-slider" x-data="myXData()" x-effect="initSlider">
  <div class="splide__track">
    <ul class="splide__list">
      <li class="splide__slide"> <img
        src="<?= $escaper->escapeHtmlAttr($imageUrl) ?>"
        alt="<?= $escaper->escapeHtml(__('Hit the court in style')) ?>"
        width="1400"
        height="800"
        loading="lazy"
        class="col-start-1 row-start-1 w-full h-[600px] sm:h-[800px] md:h-[576px] object-cover group-hover:opacity-70 transition-opacity duration-500"
    ></li>
      <li class="splide__slide"> <img
        src="<?= $escaper->escapeHtmlAttr($imageUrl) ?>"
        alt="<?= $escaper->escapeHtml(__('Hit the court in style')) ?>"
        width="1400"
        height="800"
        loading="lazy"
        class="col-start-1 row-start-1 w-full h-[600px] sm:h-[800px] md:h-[576px] object-cover group-hover:opacity-70 transition-opacity duration-500"
    ></li>
      <li class="splide__slide"> <img
        src="<?= $escaper->escapeHtmlAttr($imageUrl) ?>"
        alt="<?= $escaper->escapeHtml(__('Hit the court in style')) ?>"
        width="1400"
        height="800"
        loading="lazy"
        class="col-start-1 row-start-1 w-full h-[600px] sm:h-[800px] md:h-[576px] object-cover group-hover:opacity-70 transition-opacity duration-500"
    ></li>
    </ul>
  </div>
</section>
<script>
    function myXData () {
        return {
            initSlider() {
                if (Alpine.store('<?= HyvaSplideJSInterface::HYVA_SPLIDE_JS ?>').is_loaded) {
                    new Splide('#my-slider', {
                        type   : 'loop',
                        perPage: 3,
                        perMove: 1,
                        gap: '2rem',
                        arrows: false,
                        pagination: true,
                        autoplay: true,
                        interval: 1000,
                        speed: 1000,
                        rewind     : true,
                        rewindSpeed: 1000,
                        breakpoints: {
                            640: {
                                perPage: 1,
                                gap: '.7rem',
                            },
                            1024: {
                                perPage: 2,
                            }
                        }
                    }).mount();
                }
            }
        }
     }
</script>

